#!/usr/bin/env python3

"""Run validation for s2s based on generated test data."""

import os
import shutil
import sys
import time

from csvout import csv_row
from data import Data, Status
from gconfig import Args, Config
from generate import count_targets, generate, prune
from pyshacl import validate  # pyright: ignore[reportUnknownVariableType]
from rdflib import Graph
from render import render
from vocabulary import Vocabulary


def attempt(
    config: Config, shapes: Graph, query: str, in_graph_path: str, tries: int
) -> Data:
    """Attempt to get input an result graphs."""

    data = Data()

    for i in range(tries):
        # Load given graph, or generate fresh one.
        try:
            # If there is a given input graph, use this one.
            g = Graph()
            _ = g.parse(in_graph_path)

        except FileNotFoundError:
            # Otherwise, generate a random RDF graph.
            g = generate(config, i)
        # Attempt to prune the input graph.
        pruned = prune(config, shapes, g, max_iterations=10)
        if pruned == Status.OK or (i + 1 >= tries and Status.MISSING_TARGETS):
            if g:
                # Attempt to run query and construct output graph.
                out = g.query(query)
                if out:
                    go = Graph()
                    for triple in out:
                        go.add(
                            triple  # pyright: ignore[reportArgumentType, reportUnusedCallResult]
                        )
                    # Success: Return early.
                    data.error = pruned
                    data.in_graph = g
                    data.out_graph = go
                    return data
                else:
                    data.error = Status.EMPTY_OUTPUT
                    data.in_graph = g
            else:
                data.error = Status.EMPTY_INPUT
        else:
            data.error = pruned
            data.broken_graph = g

    # If this is the final attempt, return failure.
    return data


def store_graph(g: None | Graph, path: str, name: str, render_graphs: bool) -> None:
    """Store the given graph 'g' at 'path'."""
    if g:
        _ = g.serialize(destination=os.path.join(path, name + ".ttl"))
        if render_graphs:
            render(g, os.path.join(path, "graph_" + name + ".png"))


def run_case(validation_path: str, args: Args):
    """Run validation for one sample path."""
    # Prepare the directory.
    out_path = os.path.join(validation_path, "out")
    shutil.rmtree(out_path, ignore_errors=True)
    os.mkdir(out_path)

    # Parse the sample input shapes.
    shapes_in = Graph()
    _ = shapes_in.parse(os.path.join(validation_path, "in.json"))

    if args.render:
        render(shapes_in, os.path.join(out_path, "shapes_in.png"))

    # Parse the sample query.
    try:
        # Try to open SPARQL query.
        with open(os.path.join(validation_path, "query.sparql"), encoding="utf-8") as f:
            q = f.read()
            property_mode = False
    except FileNotFoundError:
        # Otherwise, try to open (mapped) G-CORE query.
        with open(os.path.join(validation_path, "query.gcore"), encoding="utf-8") as f:
            q = f.read()
            property_mode = True

    # Parse the output shapes generated by S2S.
    shapes_out = Graph()
    _ = shapes_out.parse(os.path.join(validation_path, "out.json"))

    if args.render:
        render(shapes_out, os.path.join(out_path, "shapes_out.png"))

    # Generate a suitable output graph.
    a = attempt(
        # Configuration for graph generation/pruning.
        Config(
            # Load the vocabulary.
            Vocabulary(
                concepts=os.path.join(validation_path, "concepts.vocabulary"),
                properties=os.path.join(validation_path, "properties.vocabulary"),
                nominals=os.path.join(validation_path, "nominals.vocabulary"),
            ),
            triples_baseline=args.number_of_triples,
            triples_increase=args.increase,
            node_to_triple_ratio=(0.25, 0.1),
            concept_property_ratio=(0.5, 0.25),
            property_label_ratio=(0.5, 0.25),
            property_mode=property_mode,
        ),
        # The input shapes.
        shapes=shapes_in,
        # The input query.
        query=q,
        # Optional explicit input graph.
        in_graph_path=os.path.join(validation_path, "in.ttl"),
        # Repeat this attempt this many times.
        tries=args.tries,
    )

    # Seriaize and render the input graph, even if there is no output.
    if a.in_graph:
        if not a.out_graph:
            name = "in_no_output"
        else:
            name = "in"
        store_graph(a.in_graph, out_path, name, args.render)
    else:
        store_graph(a.broken_graph, out_path, "in_broken", args.render)

    # Validate the result graph with out shapes.
    if not a.out_graph:
        # Failed to generate a suitable graph.
        a.validity = True
        a.out_missing_targets = -1
        a.out_total_targets = -1
        return a
    else:
        # Serialize the input and result graphs; possibly create png.
        store_graph(a.out_graph, out_path, "out", args.render)

        # Obtained suitable graph, validate against output shapes.
        is_valid, report, report_human = (  # pyright: ignore[reportUnknownVariableType]
            validate(data_graph=a.out_graph, shacl_graph=shapes_out)
        )

        # Check, whether the output graph actually includes targets.
        (missing_targets, total_targets) = count_targets(shapes_out, a.out_graph)

        # If there is a validation error, log the issues.
        if not is_valid:
            store_graph(
                report,  # pyright: ignore[reportUnknownArgumentType]
                out_path,
                "report",
                render_graphs=False,
            )
            with open(
                os.path.join(out_path, "report.txt"), mode="w", encoding="utf-8"
            ) as f:
                _ = f.write(report_human)  # pyright: ignore[reportUnknownArgumentType]

        a.validity = is_valid
        a.out_graph_file = os.path.join(out_path, "out.ttl")
        a.in_graph_file = os.path.join(out_path, "in.ttl")
        a.out_missing_targets = missing_targets
        a.out_total_targets = total_targets

        if a.error == Status.OK and missing_targets == total_targets:
            a.error = Status.MISSING_ALL_TARGETS_OUT
        elif a.error == Status.OK and missing_targets > 0:
            a.error = Status.MISSING_TARGETS_OUT
        return a


def run_one(path: str, args: Args) -> None:
    """Run, with additional detail, a single problem instance."""
    # Iterate 'repetition' times.
    for _ in range(args.repetitions):
        # Take time, and run sample.
        start_time = time.time()
        result = run_case(path, args)
        result.path = path
        result.time = time.time() - start_time
        # Print CSV entry to stdout and result file.
        csv_row(result, os.path.join(path, "out", "result.csv"))


def run_dir(subdir: str, args: Args) -> None:
    """Run validation on all samples in a test directory."""
    index = 0
    for test in os.listdir(subdir):
        index += 1
        # The (relative) path of the test sample.
        path = os.path.join(subdir, test)
        print(time.ctime(), "Running", index, path, file=sys.stderr)
        run_one(path, args)


def run_all(args: Args) -> None:
    """Run validation on all samples."""
    # TODO: Iterate *all* folders.
    run_dir(os.path.join("data", "sccq"), args)
    run_dir(os.path.join("data", "eccq"), args)
    # TODO: Add generated/
