#!/usr/bin/env python3

"""Run validation for s2s based on generated test data."""

import argparse
import os
import shutil
import sys
import time

from generate import Config, count_targets, generate, prune
from pyshacl import validate
from rdflib import Graph
from render import render
from vocabulary import Vocabulary


def make_result(error, ingraph=None, outgraph=None, broken=None):
    """Construct the result map of an attempt."""
    return {
        "error": error,
        "ingraph": ingraph,
        "insize": len(ingraph) if ingraph else -1,
        "outgraph": outgraph,
        "outsize": len(outgraph) if outgraph else -1,
        "broken_ingraph": broken,
    }


def attempt(config, shapes, query, in_graph_path, tries):
    """Attempt to get input an result graphs."""
    for _ in range(tries):
        # Load given graph, or generate fresh one.
        try:
            # If there is a given input graph, use this one.
            g = Graph()
            g.parse(in_graph_path)

        except FileNotFoundError:
            # Otherwise, generate a random RDF graph.
            g = generate(config)
        # Attempt to prune the input graph.
        pruned = prune(config, shapes, g, max_iterations=10)
        if pruned == "ok":
            if g:
                # Attempt to run query and construct output graph.
                out = g.query(query)
                if out:
                    go = Graph()
                    for triple in out:
                        go.add(triple)
                    # Success: Return early.
                    return make_result(pruned, g, go)
                else:
                    result = make_result("empty_output", g)
            else:
                result = make_result("empty_input")
        else:
            result = make_result(pruned, None, None, g)

    # If this is the final attempt, return failure.
    return result


def store_graph(g, path, name, render_graphs):
    """Store the given graph 'g' at 'path'."""
    g.serialize(destination=os.path.join(path, name + ".ttl"))
    if render_graphs:
        render(g, os.path.join(path, "graph_" + name + ".png"))


def run_case(validation_path, args):
    """Run validation for one sample path."""
    # Prepare the directory.
    out_path = os.path.join(validation_path, "out")
    shutil.rmtree(out_path, ignore_errors=True)
    os.mkdir(out_path)

    # Parse the sample input shapes.
    shapes_in = Graph()
    shapes_in.parse(os.path.join(validation_path, "in.json"))

    if args.render:
        render(shapes_in, os.path.join(out_path, "shapes_in.png"))

    # Parse the sample query.
    try:
        # Try to open SPARQL query.
        with open(os.path.join(validation_path, "query.sparql"), encoding="utf-8") as f:
            q = f.read()
            property_mode = False
    except FileNotFoundError:
        # Otherwise, try to open (mapped) G-CORE query.
        with open(os.path.join(validation_path, "query.gcore"), encoding="utf-8") as f:
            q = f.read()
            property_mode = True

    # Parse the output shapes generated by S2S.
    shapes_out = Graph()
    shapes_out.parse(os.path.join(validation_path, "out.json"))

    if args.render:
        render(shapes_out, os.path.join(out_path, "shapes_out.png"))

    # Generate a suitable output graph.
    a = attempt(
        # Configuration for graph generation/pruning.
        Config(
            # Load the vocabulary.
            Vocabulary(
                concepts=os.path.join(validation_path, "concepts.vocabulary"),
                properties=os.path.join(validation_path, "properties.vocabulary"),
                nominals=os.path.join(validation_path, "nominals.vocabulary"),
            ),
            number_of_triples=args.number_of_triples,
            node_to_triple_ratio=(0.5, 0.25),
            concept_property_ratio=(0.5, 0.25),
            property_label_ratio=(0.5, 0.25),
            property_mode=property_mode,
        ),
        # The input shapes.
        shapes=shapes_in,
        # The input query.
        query=q,
        # Optional explicit input graph.
        in_graph_path=os.path.join(validation_path, "in.ttl"),
        # Repeat this attempt this many times.
        tries=100,
    )

    # Seriaize and render the input graph, even if there is no output.
    if a["ingraph"]:
        if not a["outgraph"]:
            name = "in_no_output"
        else:
            name = "in"
        store_graph(a["ingraph"], out_path, name, args.render)
    else:
        store_graph(a["broken_ingraph"], out_path, "in_broken", args.render)

    # Validate the result graph with out shapes.
    if not a["outgraph"]:
        # Failed to generate a suitable graph.
        return a | {
            "validity": None,
            "out_missing_targets": -1,
            "out_total_targets": -1,
        }
    else:
        # Serialize the input and result graphs; possibly create png.
        store_graph(a["outgraph"], out_path, "out", args.render)

        # Obtained suitable graph, validate against output shapes.
        is_valid, report, report_human = validate(
            data_graph=a["outgraph"], shacl_graph=shapes_out
        )

        # Check, whether the output graph actually includes targets.
        (missing_targets, total_targets) = count_targets(shapes_out, a["outgraph"])

        # If there is a validation error, log the issues.
        if not is_valid:
            store_graph(report, out_path, "report", render_graphs=False)
            with open(
                os.path.join(out_path, "report.txt"), mode="w", encoding="utf-8"
            ) as f:
                f.write(report_human)

        return a | {
            "validity": is_valid,
            "outgraph": os.path.join(out_path, "out.ttl"),
            "ingraph": os.path.join(out_path, "in.ttl"),
            "out_missing_targets": missing_targets,
            "out_total_targets": total_targets,
        }


def run_one(path, args):
    """Run, with additional detail, a single problem instance."""
    # Iterate 'repetition' times.
    for _ in range(args.repetitions):
        # Take time, and run sample.
        start_time = time.time()
        result = run_case(path, args) | {"path": path, "time": time.time() - start_time}

        # Print CSV entry to stdout and result file.
        csv_row(result, os.path.join(path, "out", "result.csv"))


def run_dir(subdir, args):
    """Run validation on all samples in a test directory."""
    index = 0
    for test in os.listdir(subdir):
        index += 1
        # The (relative) path of the test sample.
        path = os.path.join(subdir, test)
        print(time.time(), "Running", index, path, file=sys.stderr)
        run_one(path, args)


def run_all(args):
    """Run validation on all samples."""
    # TODO: Iterate *all* folders.
    run_dir(os.path.join("data", "sccq"), args)
    run_dir(os.path.join("data", "eccq"), args)
    # TODO: Add generated/


def csv_header():
    """Print csv header."""
    return (
        "test case,input triples,result triples,"
        "missing targets,total targets,"
        "evaluation time,error,valid"
    )


def csv_row(data, path=None):
    """Print CSV data to stdout and path-based result file."""
    csv = (
        "{path},{insize},{outsize},"
        "{out_missing_targets},{out_total_targets},"
        "{time},{error},{validity}"
    ).format(**data)
    if path:
        with open(path, mode="w", encoding="utf-8") as f:
            f.write(csv)
    print(csv)


def csv_gather():
    """Print all csv results, including header."""
    for subdir in os.listdir("data"):
        for test in os.listdir(os.path.join("data", subdir)):
            path = os.path.join("data", subdir, test, "out", "result.csv")
            try:
                with open(path, encoding="utf-8") as f:
                    print(f.read())
            except IOError:
                pass


def main():
    """Command line interface for S2S validation."""
    # Define the argument parser.
    parser = argparse.ArgumentParser(
        prog="s2s-validation",
        description="Validation tools for S2S.",
        epilog="see https://github.com/softlang/s2s",
    )

    parser = argparse.ArgumentParser(prog="PROG")
    mode = parser.add_mutually_exclusive_group(required=True)

    # Execution mode.
    mode.add_argument(
        "-a",
        "--run-all",
        action="store_true",
        help="run all known validation cases in 'data'",
    )
    mode.add_argument("-s", "--single", help="single test case folder")
    mode.add_argument(
        "-d", "--directory", help="multiple test case folders in directory"
    )
    mode.add_argument(
        "-g",
        "--gather-results",
        action="store_true",
        help="show available results in 'data'",
    )

    # Global options.
    parser.add_argument(
        "-r",
        "--render",
        action="store_true",
        help="generate .png files (requires graphviz)",
    )
    parser.add_argument(
        "-n",
        "--number-of-triples",
        action="store",
        default=100,
        type=int,
        help="Number of triples (default: 100)",
    )
    parser.add_argument(
        "-x",
        "--repetitions",
        action="store",
        default=1,
        type=int,
        help="Number of repititions per sample (default: 1)",
    )

    # Parse CLI
    args = parser.parse_args()

    # In any case, print CSV header for output.
    print(csv_header())

    # Execute the required mode (based on the 'mode' arguments).
    if args.single:
        run_one(args.single, args)
    elif args.directory:
        run_dir(args.directory, args)
    elif args.run_all:
        run_all(args)
    elif args.gather_results:
        csv_gather()
    else:
        pass  # Mode is required, this is never reached.


if __name__ == "__main__":
    main()
